name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: windows-latest


    steps:

    - name: Download

      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract

      run: Expand-Archive ngrok.zip
    - run: remove-item -fo D:\a\vds\vds\ngrok.zip

    - name: Auth

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: net stop was /y
    - run: New-NetFirewallRule -DisplayName "MySql" -Direction inbound -Profile Any -Action Allow -LocalPort 3306 -Protocol TCP
    - run: Invoke-WebRequest https://kluedutr-my.sharepoint.com/:u:/g/personal/1216706031_ogr_klu_edu_tr/EVr7kUwnanVGrZjGhHorzngBYNe8DszQbPtVnkKJ8pCZWA?download=1 -OutFile data.ps1
    - run: .\data.ps1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Ahmetarat16.." -Force)

    - name: Create Tunnel

      run: .\ngrok\ngrok.exe tcp 3389
